name: Compliance
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  licenses:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install -y moreutils

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - uses: actions/checkout@v2

      - run: .github/workflows/compliance/check-licenses.sh
