name: Go
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build-test:

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - run: sudo .github/workflows/setup-go.sh # TODO: downgrade to v1.18 once available

      - run: go build -gcflags="-m" ./...

      - run: go test -v -race ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: sudo .github/workflows/setup-go.sh # TODO: downgrade to v1.18 once available

      - name: Run staticcheck ./...
        run: |
            go install honnef.co/go/tools/cmd/staticcheck@df71e5d0e0ed317ebf43e6e59cf919430fa4b8f2
            ~/go/bin/staticcheck ./...

  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: sudo .github/workflows/setup-go.sh # TODO: downgrade to v1.18 once available

      - run: go vet ./...

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: sudo .github/workflows/setup-go.sh # TODO: downgrade to v1.18 once available

      - name: Run gofmt -d .
        run: |
            fmtvar="$(gofmt -d .)"
            echo "$fmtvar"
            test -z "$fmtvar"
